version: "3.8"

services:
  splunk:
    image: splunk/splunk:latest
    container_name: splunk
    ports:
      - "8000:8000"   # Web UI
      - "8088:8088"   # HTTP Event Collector
      - "9997:9997"   # Forwarder port
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_GENERAL_TERMS=--accept-sgt-current-at-splunk-com
      - SPLUNK_PASSWORD=${SPLUNK_PASSWORD}
      - SPLUNK_USER=splunk
    volumes:
      - ./data:/opt/splunk/var
      - ./etc:/opt/splunk/etc
    restart: unless-stopped
